_base_: '../_base_/cityscapes.yml'

model:
  type: OCRNet
  backbone:
    type: HRNet_W48
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
  backbone_indices: [0]
  num_classes: 19

optimizer:
  type: sgd
  weight_decay: 0.0002


iters: 60000
batch_size: 2


loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
  coef: [1, 0.4]

# loss:
#   types:
#     - type: CrossEntropyLoss
#     - type: PixelContrastCrossEntropyLoss
#       temperature: 0.1
#       base_temperature: 0.07
#       ignore_index: 255
#       max_samples: 1024
#       max_views: 100
#   coef: [1, 0.1]
  
